### ISSUE TITLE
libinput_dispatch twice in EventHub::HandleEvents() ?

### ISSUE THREAD

**Issue by thekingofkings** [kkspeed/NaiveWM#1]
Why dispatch event twice?
Is this a bug?

**Comment by reasonsolo** [comment]
code like shit but not a bug
dispatching events outside loop to make sure while-test goes on and dispatching inside the loop to make sure all active events are handled

**Comment by thekingofkings** [comment]
在获取下一个event的时候，先用`libinput_dispatch`read file descriptors看有没有event，有的话就`libinput_get_event`。

所以问题其实是
1）为什么while循环不是以`libinput_dispatch`做条件 。 
2）每次`libinput_dispatch`之前要不要`libinput_get_fd`。

**Comment by kkspeed** [comment]
@thekingofkings 看libinput 的code: 
https://github.com/jadahl/libinput/blob/master/src/libinput.c#L553
https://github.com/jadahl/libinput/blob/master/src/libinput.c#L839

必须要call libinput_dispatch, libinput_get_event才能拿到event. libinput_dispatch负责从fd里读event, libinput_get_event负责从queue里面读event.
